[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
kuroshio = "GRG9CqaYABVi2Z67CBFbkq9vHC8VJ2CtvCtmqs3woHqE"

[programs.devnet]
kuroshio = "GRG9CqaYABVi2Z67CBFbkq9vHC8VJ2CtvCtmqs3woHqE"

[provider]
cluster = "devnet"
wallet = "keys/deployer.json"

[scripts]
test = "cargo test -p kuroshio-math"
